apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: hello-rollout
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-container
        image: xerus1007/xerus-k8s-sample-test:v1.0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
  strategy:
    blueGreen:
      activeService: hello-active
      previewService: hello-preview
      autoPromotionEnabled: false  # 需手動 promote，較安全
